<%@ Page Language="C#" MasterPageFile="~/Site.master" CodeBehind="ParentChildren.aspx.cs" Inherits="DynamicDataProject.SamplePages.ParentChildren" %>

<%@ Register src="~/DynamicData/Content/GridViewPager.ascx" tagname="GridViewPager" tagprefix="asp" %>

<asp:Content ID="headContent" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:DynamicDataManager ID="DynamicDataManager1" runat="server" AutoLoadForeignKeys="true" />

    <h2><%= GridDataSource.GetTable().DisplayName %></h2>

    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
            <asp:ValidationSummary ID="ValidationSummary1" runat="server" EnableClientScript="true"
                HeaderText="List of validation errors" />
            <asp:DynamicValidator runat="server" ID="GridView1Validator" ControlToValidate="GridView1" Display="None" />
            <asp:DynamicValidator runat="server" ID="GridView2Validator" ControlToValidate="GridView2" Display="None" />

            <asp:GridView ID="GridView1" runat="server" DataSourceID="GridDataSource" EnablePersistedSelection="true"
                AutoGenerateSelectButton="True" AutoGenerateEditButton="True" AutoGenerateDeleteButton="true"
                AllowPaging="True" AllowSorting="True" OnDataBound="OnGridViewDataBound"
                OnSelectedIndexChanging="OnGridViewSelectedIndexChanging"
                
                OnRowCreated="OnGridViewRowCreated" CssClass="gridview">

                <PagerStyle CssClass="footer" />        
                <SelectedRowStyle CssClass="selected" />
                <PagerTemplate>
                    <asp:GridViewPager runat="server" />
                </PagerTemplate>
                <EmptyDataTemplate>
                    There are currently no items in this table.
                </EmptyDataTemplate>
            </asp:GridView>

            <aspX:LinqDataSource ID="GridDataSource" runat="server" EnableDelete="true" EnableUpdate="true" ContextTypeName="DynamicDataProject.NorthwindDataContext"
                TableName="Categories">
            </aspX:LinqDataSource>
            
            <asp:Panel ID="DetailsPanel" runat="server">
                <br /><br />
                
                <asp:GridView ID="GridView2" runat="server" DataSourceID="DetailsDataSource" CssClass="gridview"
                    AutoGenerateDeleteButton="true" AutoGenerateEditButton="true"
                    AllowPaging="true" AllowSorting="true" OnPreRender="OnDetailsViewPreRender" >
                    <EmptyDataTemplate>
                        No items matching the given criteria.
                    </EmptyDataTemplate>
                    <PagerTemplate>
                        <asp:GridViewPager ID="GridViewPager1" runat="server" />
                    </PagerTemplate>
                    <PagerStyle CssClass="footer" />        
                </asp:GridView>
            
                <aspX:LinqDataSource ID="DetailsDataSource" runat="server" EnableDelete="true" EnableInsert="true"
                    EnableUpdate="true" ContextTypeName="DynamicDataProject.NorthwindDataContext" TableName="Products">
                </aspX:LinqDataSource>
                
                <aspX:QueryExtender TargetControlID="DetailsDataSource" runat="server">
                    <asp:ControlFilterExpression ControlID="GridView1" Column="Category" />
                </aspX:QueryExtender>
            </asp:Panel>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>

