//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Web.Preview.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PreviewWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PreviewWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Web.Preview.Resources.PreviewWeb", typeof(PreviewWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create BridgeHandler type for: {0}.
        /// </summary>
        internal static string BridgeHandler_CannotCreate {
            get {
                return ResourceManager.GetString("BridgeHandler_CannotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load BridgeHandler type for: {0}.
        /// </summary>
        internal static string BridgeHandler_CannotLoad {
            get {
                return ResourceManager.GetString("BridgeHandler_CannotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BridgeRestProxy: passed a null or empty URL..
        /// </summary>
        internal static string BridgeRestProxy_EmptyUrl {
            get {
                return ResourceManager.GetString("BridgeRestProxy_EmptyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; node required..
        /// </summary>
        internal static string BridgeService_NodeRequired {
            get {
                return ResourceManager.GetString("BridgeService_NodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPathBridgeTransformer requires a selectedNodes dictionary..
        /// </summary>
        internal static string XPathBridgeTransformer_RequiresSelectNodes {
            get {
                return ResourceManager.GetString("XPathBridgeTransformer_RequiresSelectNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPathBridgeTransformer requires a selector attribute..
        /// </summary>
        internal static string XPathBridgeTransformer_RequiresSelectorAttribute {
            get {
                return ResourceManager.GetString("XPathBridgeTransformer_RequiresSelectorAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPathBridgeTransformer can only transform a string..
        /// </summary>
        internal static string XPathBridgeTransformer_StringOnly {
            get {
                return ResourceManager.GetString("XPathBridgeTransformer_StringOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XsltBridgeTransformer can only transform a string..
        /// </summary>
        internal static string XsltBridgeTransformer_StringOnly {
            get {
                return ResourceManager.GetString("XsltBridgeTransformer_StringOnly", resourceCulture);
            }
        }
    }
}
