//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Web.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MvcResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Web.Mvc.Resources.MvcResources", typeof(MvcResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required anti-forgery token was not supplied or was invalid..
        /// </summary>
        internal static string AntiForgeryToken_ValidationFailed {
            get {
                return ResourceManager.GetString("AntiForgeryToken_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a valid &apos;{1}&apos;..
        /// </summary>
        internal static string DefaultModelBinder_CouldNotConvert {
            get {
                return ResourceManager.GetString("DefaultModelBinder_CouldNotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot route to class named &apos;Controller&apos;.
        /// </summary>
        internal static string ExpressionHelper_CannotRouteToController {
            get {
                return ResourceManager.GetString("ExpressionHelper_CannotRouteToController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must be a method call.
        /// </summary>
        internal static string ExpressionHelper_MustBeMethodCall {
            get {
                return ResourceManager.GetString("ExpressionHelper_MustBeMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller name must end in &apos;Controller&apos;.
        /// </summary>
        internal static string ExpressionHelper_TargetMustEndInController {
            get {
                return ResourceManager.GetString("ExpressionHelper_TargetMustEndInController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model binder can only be used with models of type &apos;{0}&apos;..
        /// </summary>
        internal static string ModelBinder_WrongModelType {
            get {
                return ResourceManager.GetString("ModelBinder_WrongModelType", resourceCulture);
            }
        }
    }
}
