//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Web.Preview.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PreviewWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PreviewWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Web.Preview.Resources.PreviewWeb", typeof(PreviewWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument should be of type DataRow..
        /// </summary>
        internal static string ArgumentShouldBeDataRow {
            get {
                return ResourceManager.GetString("ArgumentShouldBeDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument should be of type DataSet..
        /// </summary>
        internal static string ArgumentShouldBeDataSet {
            get {
                return ResourceManager.GetString("ArgumentShouldBeDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument should be of type DataTable..
        /// </summary>
        internal static string ArgumentShouldBeDataTable {
            get {
                return ResourceManager.GetString("ArgumentShouldBeDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page cannot be null. Please ensure that this operation is being performed in the context of an ASP.NET request..
        /// </summary>
        internal static string Common_PageCannotBeNull {
            get {
                return ResourceManager.GetString("Common_PageCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control with ID &apos;{0}&apos; requires a ScriptManager on the page. The ScriptManager must appear before any controls that need it..
        /// </summary>
        internal static string Common_ScriptManagerRequired {
            get {
                return ResourceManager.GetString("Common_ScriptManagerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getDataMethodNames should contain at least one name..
        /// </summary>
        internal static string DataAdapterAttribute_AtLeastOneName {
            get {
                return ResourceManager.GetString("DataAdapterAttribute_AtLeastOneName", resourceCulture);
            }
        }
    }
}
